name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v2
      with:
        name: HelloWorld
        path: ./ConsoleApp2/bin/Debug/net5.0/ConsoleApp2.exe
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
  send-to-telegram:

    runs-on: ubuntu-latest

    needs: jobs

    steps:
      - name: send default message
        uses: appleboy/telegram-action@master
        with:
            to: ${{secrets.TELEGRAM_TO_DEBUG}}
            token: ${{secrets.TELEGRAM_TOKEN_DEBUG}}
            message: Hello from .NET
            document: ./ConsoleApp2/bin/Debug/net5.0/ConsoleApp2.exe